persistence:
  enabled: true
  storageClass: rook-ceph-block
adminPassword: qhdkscjfwj!@
configPassword: qhdkscjfwj!@

service:
  type: LoadBalancer
  loadBalancerIP: 192.168.100.29

env:
  LDAP_ORGANISATION: "SELab Inc."
  LDAP_DOMAIN: "selab.co.kr"

ltb-passwd:
  enabled : true
  ingress:
    enabled: true
    annotations: {}
    host: "ssl-ldap2.local"
  ldap:
    server: ldap://192.168.100.29
    searchBase: dc=selab,dc=co,dc=kr
    bindDN: cn=admin,dc=selab,dc=co,dc=kr
    bindPWKey: LDAP_ADMIN_PASSWORD
