version: '3.7'

services:
  minio1:
    image: minio/minio:RELEASE.2020-08-26T00-00-49Z
    hostname: minio1
    volumes:
      - minio1-data:/export
      - minio1-data1:/data1
      - minio1-data2:/data2
      - minio1-data2:/data3
      - minio1-data2:/data4
    ports:
      - "9002:9000"
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio1==true
    command: server http://minio{1...4}/export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio:RELEASE.2020-08-26T00-00-49Z
    hostname: minio2
    volumes:
      - minio2-data:/export
      - minio2-data1:/data1
      - minio2-data2:/data2
      - minio2-data2:/data3
      - minio2-data2:/data4
    ports:
      - "9003:9000"
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio2==true
    command: server http://minio{1...4}/export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: minio/minio:RELEASE.2020-08-26T00-00-49Z
    hostname: minio3
    volumes:
      - minio3-data:/export
      - minio3-data1:/data1
      - minio3-data2:/data2
      - minio3-data3:/data3
      - minio3-data4:/data4
    ports:
      - "9004:9000"
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio3==true
    command: server http://minio{1...4}/export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    image: minio/minio:RELEASE.2020-08-26T00-00-49Z
    hostname: minio4
    volumes:
      - minio4-data:/export
      - minio4-data1:/data1
      - minio4-data2:/data2
      - minio4-data2:/data3
      - minio4-data2:/data4
    ports:
      - "9005:9000"
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio4==true
    command: server http://minio{1...4}/export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio1-data:
  minio1-data1:
  minio1-data2:
  minio1-data3:
  minio1-data4:
  minio2-data:
  minio2-data1:
  minio2-data2:
  minio2-data3:
  minio2-data4:
  minio3-data:
  minio3-data1:
  minio3-data2:
  minio3-data3:
  minio3-data4:
  minio4-data:
  minio4-data1:
  minio4-data2:
  minio4-data3:
  minio4-data4:

networks:
  minio_distributed:
    driver: overlay

secrets:
  secret_key:
    external: true
  access_key:
    external: true